#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

API_URL="https://api.github.com/repos/joomla/joomla-cms/releases/latest"
VERSION="$(curl -s $API_URL | jq -r '.tag_name')"

URL="https://github.com/joomla/joomla-cms/releases/download/$VERSION/Joomla_$VERSION-Stable-Full_Package.tar.gz"

dl $URL /usr/local/src

