#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

GH_API=https://api.github.com/repos/joomla/joomla-cms/releases/latest
LATEST=$(curl -s $GH_API | grep -oP '"tag_name": "\K(.*)(?=")')
VERSION=${LATEST#v}

URL="https://github.com/joomla/joomla-cms/releases/download/$VERSION/Joomla_$VERSION-Stable-Full_Package.tar.gz"

dl $URL /usr/local/src

